global:
  scrape_interval: 15s
  external_labels:
    monitor: 'first-monitor'

rule_files:
  - /etc/prometheus/rules.yml

# alerting:
#   alertmanagers:
#     - static_configs:
#       - targets: ['192.168.1.180:9093']
#         #- targets: ['localhost:9093']

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:          #tartget IP
      - targets: ['127.0.0.1:9090']

  - job_name: 'node_exporter'
    scrape_interval: 10s
    file_sd_configs:
      - files:
        - node.yml
    #static_configs:
    #  - targets: ['192.168.1.180:9100']
    #  - targets: ['192.168.1.110:9100']
    #  - targets: ['192.168.1.25:9100']
    #  - targets: ['192.168.1.90:9100']
    #  - targets: ['192.168.1.183:9100']
    #  - targets: ['192.168.1.230:9100']

  - job_name: 'cadvisor'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.1.183:8080']
      - targets: ['192.168.1.199:8080']
        #- targets: ['192.168.1.110:8088']
      - targets: ['192.168.1.180:8080']
        #- targets: ['192.168.1.25:8088']
        #- targets: ['192.168.1.90:8088']
        #- targets: ['192.168.1.100:8080']
        # - targets: ['192.168.1.7:8088']

  - job_name: 'snmp'
    static_configs:
      - targets:
        - 192.168.1.199  # SNMP device.
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.1.199:9116  # The SNMP exporter's real hostname:port.