version: "3"

services:
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
      - /etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - 8006:8006
