---
# tasks file for all
 - name: install comopuslory packages 
   apt:
     name: "{{ item }}"
     state: latest
   #vars:
     #- var1=80
   loop:
     - curl
     - tree
     - wget
     - net-tools
     - vim
     - python3
     - network-manager
     - awscli
     - ntpdate
     - unzip
     - iftop
     - tcpdump
     - python-pip

 - name: Set Timezone to Americal/Vancouver
   timezone:
     name: America/Vancouver

 - name: check if jalen is defined in the file
   lineinfile:
     state: absent
     path: "/root/.bashrc"
     regexp: "^alias addit"
   check_mode: true
   changed_when: false
   register: check_result

 - name: show the check result
   debug:
     msg:
       "{{ check_result }}"

 - name: define jalen if it is not defined
   blockinfile:
     state: present
     path: "/root/.bashrc"
     block: |
       alias vi='vim'
       alias n='netstat -nlpt'
       alias i='ip a'
       alias c='cd /var/log'
   when: check_result.found == 0
