---
# tasks file for node_exporter
- name: Create a directory on the rmeote host for storing the docker-compse file
  file:
    name: /etc/node_exporter
    state: directory

- name: Copy the docker-compose file to the remote host
  copy:
    src: /etc/ansible/roles/node_expoorter/templates/docker-compose.yml
    dest: /etc/node_exporter/docker-compose.yml

- name: Deplopy node_exporter on the remote host
  docker_compose:
    project_src: /etc/node_exporter/
    state: present